package preprocessing.diffpreprocessor;

public enum ModificationType {

	CLASSADDITION, CLASSREMOVAL, 
	ADDSMEMBER, ADDSIMPORT, ADDSINTERFACE, ADDSSUPERCLASS, 
	MODIFIESMEMBER, MODIFIESPACKAGE, MODIFIESIMPORT, MODIFIESINTERFACE, MODIFIESSUPERCLASS,
	REMOVESMEMBER, REMOVESIMPORT, REMOVESINTERFACE, REMOVESSUPERCLASS
	
}
