package preprocessing.diffpreprocessor;

public enum ModificationType {

	CLASSADDITION, CLASSREMOVAL, 
	ADDSFIELD, ADDSMETHOD, ADDSIMPORT, ADDSINTERFACE, ADDSSUPERCLASS, 
	MODIFIESFIELD, MODIFIESMETHOD, MODIFIESPACKAGE, MODIFIESIMPORT, MODIFIESINTERFACE, MODIFIESSUPERCLASS,
	REMOVESFIELD, REMOVESMETHOD, REMOVESIMPORT, REMOVESINTERFACE, REMOVESSUPERCLASS
	
}
